# Podfile

# Set the deployment target to iOS 13.0 for the entire project
platform :ios, '14.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'AAIROS' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Uncomment the next line to enable Flipper.
    # :flipper_configuration => FlipperConfiguration.enabled(["Flipper-Folly"]),
    :production => false
  )

  target 'AAIROSTests' do
    inherit! :complete
    # Ensure the test target also has the same deployment target
  end

  # If you have Flipper installed, you should uncomment the following line
  # use_flipper!({ 'Flipper' => '0.164.0' }) # You can specify the Flipper version you want to use

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
